<a href="https://colab.research.google.com/github/sanvi1510/Pytorch/blob/main/Pytorch_lec_3_simple_nn_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

Processing data

In [18]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [19]:
df.shape

(569, 33)

In [20]:
df=df.drop(columns=["Unnamed: 32","id"])
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [21]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [22]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
77,18.05,16.15,120.20,1006.0,0.10650,0.21460,0.16840,0.10800,0.2152,0.06673,...,22.39,18.91,150.10,1610.0,0.14780,0.5634,0.37860,0.21020,0.3751,0.11080
250,20.94,23.56,138.90,1364.0,0.10070,0.16060,0.27120,0.13100,0.2205,0.05898,...,25.58,27.00,165.30,2010.0,0.12110,0.3172,0.69910,0.21050,0.3126,0.07849
127,19.00,18.91,123.40,1138.0,0.08217,0.08028,0.09271,0.05627,0.1946,0.05044,...,22.32,25.73,148.20,1538.0,0.10210,0.2264,0.32070,0.12180,0.2841,0.06541
265,20.73,31.12,135.70,1419.0,0.09469,0.11430,0.13670,0.08646,0.1769,0.05674,...,32.49,47.16,214.00,3432.0,0.14010,0.2644,0.34420,0.16590,0.2868,0.08218
149,13.74,17.91,88.12,585.0,0.07944,0.06376,0.02881,0.01329,0.1473,0.05580,...,15.34,22.46,97.19,725.9,0.09711,0.1824,0.15640,0.06019,0.2350,0.07014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
545,13.62,23.23,87.19,573.2,0.09246,0.06747,0.02974,0.02443,0.1664,0.05801,...,15.35,29.09,97.58,729.8,0.12160,0.1517,0.10490,0.07174,0.2642,0.06953
547,10.26,16.58,65.85,320.8,0.08877,0.08066,0.04358,0.02438,0.1669,0.06714,...,10.83,22.04,71.08,357.4,0.14610,0.2246,0.17830,0.08333,0.2691,0.09479
255,13.96,17.05,91.43,602.4,0.10960,0.12790,0.09789,0.05246,0.1908,0.06130,...,16.39,22.07,108.10,826.0,0.15120,0.3262,0.32090,0.13740,0.3068,0.07957
62,14.25,22.15,96.42,645.7,0.10490,0.20080,0.21350,0.08653,0.1949,0.07292,...,17.67,29.51,119.10,959.5,0.16400,0.6247,0.69220,0.17850,0.2844,0.11320
349,11.95,14.96,77.23,426.7,0.11580,0.12060,0.01171,0.01787,0.2459,0.06581,...,12.81,17.72,83.09,496.2,0.12930,0.1885,0.03122,0.04766,0.3124,0.07590

In [23]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [24]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [25]:
X_train

array([[ 1.10116114, -0.77439752,  1.14718662, ...,  1.4252129 ,
         1.34920355,  1.53510109],
       [ 1.92294931,  0.95420774,  1.91761644, ...,  1.42976207,
         0.35255509, -0.31252726],
       [ 1.37129912, -0.13054455,  1.27902488, ...,  0.08472571,
        -0.10191662, -1.06049937],
       ...,
       [-0.06185394, -0.56444546, -0.03812172, ...,  0.32128227,
         0.26006611, -0.2507681 ],
       [ 0.02060923,  0.62528285,  0.16746356, ...,  0.94451783,
        -0.0971327 ,  1.67234368],
       [-0.63340903, -1.05200079, -0.62315399, ..., -1.03952452,
         0.34936581, -0.46063489]])

In [26]:
y_train

array([1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0])

In [27]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [28]:
X_train_tensor

tensor([[ 1.1012, -0.7744,  1.1472,  ...,  1.4252,  1.3492,  1.5351],
        [ 1.9229,  0.9542,  1.9176,  ...,  1.4298,  0.3526, -0.3125],
        [ 1.3713, -0.1305,  1.2790,  ...,  0.0847, -0.1019, -1.0605],
        ...,
        [-0.0619, -0.5644, -0.0381,  ...,  0.3213,  0.2601, -0.2508],
        [ 0.0206,  0.6253,  0.1675,  ...,  0.9445, -0.0971,  1.6723],
        [-0.6334, -1.0520, -0.6232,  ..., -1.0395,  0.3494, -0.4606]],
       dtype=torch.float64)

Building Model

In [44]:
class Nueralnetwork():

  def __init__(self,X):

    self.weights=torch.randn(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z=torch.sigmoid(torch.matmul(X,self.weights)+self.bias)
    y_pred=torch.sigmoid(z)
    return y_pred

  def loss(self,y_pred,y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
    return loss

In [57]:
learning_rate=0.1
epochs=25

In [58]:
model=Nueralnetwork(X_train_tensor)

In [59]:
model.weights

tensor([[-0.0266],
        [-0.8495],
        [ 0.5687],
        [ 0.4242],
        [ 0.3610],
        [-1.9229],
        [ 0.3377],
        [-1.0080],
        [-1.3433],
        [ 0.5320],
        [ 0.5451],
        [-1.4132],
        [ 0.5129],
        [ 0.4758],
        [-3.2782],
        [ 0.4959],
        [-1.3572],
        [ 0.3321],
        [-0.6835],
        [-0.0420],
        [ 0.5986],
        [-0.5885],
        [-0.6307],
        [-0.2217],
        [-1.8220],
        [ 0.4655],
        [-0.0753],
        [ 2.2551],
        [ 2.0665],
        [ 0.2512]], dtype=torch.float64, requires_grad=True)

training pipeline

In [63]:
for epoch in range(epochs):
  #forward pass
  y_pred=model.forward(X_train_tensor)
  #loss calculation
  loss=model.loss(y_pred,y_train_tensor)
  print(epoch,"loss:",loss)
  #backward pass
  loss.backward()
  #updation
   #off.no grad during upadation
  with torch.no_grad():
    model.weights-=learning_rate*model.weights.grad
    model.bias-=learning_rate*model.bias.grad
    #on grad.zero to stop accumlation
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    print(epoch," weights:", model.weights)
    print(epoch,"bais:",model.bias)

0 loss: tensor(0.8126, dtype=torch.float64, grad_fn=<NegBackward0>)
0  weights: tensor([[-0.0264],
        [-0.8517],
        [ 0.5690],
        [ 0.4251],
        [ 0.3616],
        [-1.9219],
        [ 0.3374],
        [-1.0076],
        [-1.3413],
        [ 0.5343],
        [ 0.5441],
        [-1.4108],
        [ 0.5121],
        [ 0.4757],
        [-3.2704],
        [ 0.4976],
        [-1.3563],
        [ 0.3328],
        [-0.6802],
        [-0.0377],
        [ 0.5990],
        [-0.5914],
        [-0.6305],
        [-0.2205],
        [-1.8200],
        [ 0.4654],
        [-0.0756],
        [ 2.2558],
        [ 2.0691],
        [ 0.2525]], dtype=torch.float64, requires_grad=True)
0 bais: tensor([-0.0421], dtype=torch.float64, requires_grad=True)
1 loss: tensor(0.8125, dtype=torch.float64, grad_fn=<NegBackward0>)
1  weights: tensor([[-0.0264],
        [-0.8517],
        [ 0.5690],
        [ 0.4252],
        [ 0.3617],
        [-1.9219],
        [ 0.3374],
        [-1.0076],
        [-1.3412],
        [ 0.5344],
        [ 0.5441],
        [-1.4107],
        [ 0.5120],
        [ 0.4757],
        [-3.2701],
        [ 0.4976],
        [-1.3563],
        [ 0.3328],
        [-0.6801],
        [-0.0375],
        [ 0.5990],
        [-0.5915],
        [-0.6305],
        [-0.2205],
        [-1.8199],
        [ 0.4654],
        [-0.0756],
        [ 2.2558],
        [ 2.0692],
        [ 0.2525]], dtype=torch.float64, requires_grad=True)
1 bais: tensor([-0.0437], dtype=torch.float64, requires_grad=True)
2 loss: tensor(0.8125, dtype=torch.float64, grad_fn=<NegBackward0>)
2  weights: tensor([[-0.0264],
        [-0.8518],
        [ 0.5690],
        [ 0.4252],
        [ 0.3617],
        [-1.9218],
        [ 0.3374],
        [-1.0076],
        [-1.3411],
        [ 0.5345],
        [ 0.5440],
        [-1.4106],
        [ 0.5120],
        [ 0.4757],
        [-3.2698],
        [ 0.4977],
        [-1.3563],
        [ 0.3329],
        [-0.6799],
        [-0.0374],
        [ 0.5990],
        [-0.5916],
        [-0.6305],
        [-0.2205],
        [-1.8198],
        [ 0.4653],
        [-0.0756],
        [ 2.2558],
        [ 2.0693],
        [ 0.2526]], dtype=torch.float64, requires_grad=True)
2 bais: tensor([-0.0453], dtype=torch.float64, requires_grad=True)
3 loss: tensor(0.8125, dtype=torch.float64, grad_fn=<NegBackward0>)
3  weights: tensor([[-0.0263],
        [-0.8519],
        [ 0.5690],
        [ 0.4252],
        [ 0.3617],
        [-1.9218],
        [ 0.3374],
        [-1.0076],
        [-1.3410],
        [ 0.5346],
        [ 0.5440],
        [-1.4105],
        [ 0.5120],
        [ 0.4757],
        [-3.2695],
        [ 0.4978],
        [-1.3562],
        [ 0.3329],
        [-0.6798],
        [-0.0372],
        [ 0.5990],
        [-0.5917],
        [-0.6305],
        [-0.2204],
        [-1.8198],
        [ 0.4653],
        [-0.0756],
        [ 2.2559],
        [ 2.0693],
        [ 0.2526]], dtype=torch.float64, requires_grad=True)
3 bais: tensor([-0.0469], dtype=torch.float64, requires_grad=True)
4 loss: tensor(0.8124, dtype=torch.float64, grad_fn=<NegBackward0>)
4  weights: tensor([[-0.0263],
        [-0.8520],
        [ 0.5690],
        [ 0.4253],
        [ 0.3617],
        [-1.9217],
        [ 0.3374],
        [-1.0076],
        [-1.3409],
        [ 0.5347],
        [ 0.5440],
        [-1.4104],
        [ 0.5119],
        [ 0.4757],
        [-3.2692],
        [ 0.4978],
        [-1.3562],
        [ 0.3329],
        [-0.6797],
        [-0.0370],
        [ 0.5990],
        [-0.5918],
        [-0.6305],
        [-0.2204],
        [-1.8197],
        [ 0.4653],
        [-0.0756],
        [ 2.2559],
        [ 2.0694],
        [ 0.2527]], dtype=torch.float64, requires_grad=True)
4 bais: tensor([-0.0486], dtype=torch.float64, requires_grad=True)
5 loss: tensor(0.8124, dtype=torch.float64, grad_fn=<NegBackward0>)
5  weights: tensor([[-0.0263],
        [-0.8521],
        [ 0.5690],
        [ 0.4253],
        [ 0.3618],
        [-1.9217],
        [ 0.3374],
        [-1.0076],
        [-1.3409],
        [ 0.5348],
        [ 0.5439],
        [-1.4103],
        [ 0.5119],
        [ 0.4756],
        [-3.2689],
        [ 0.4979],
        [-1.3561],
        [ 0.3329],
        [-0.6795],
        [-0.0369],
        [ 0.5990],
        [-0.5919],
        [-0.6305],
        [-0.2203],
        [-1.8196],
        [ 0.4653],
        [-0.0757],
        [ 2.2559],
        [ 2.0695],
        [ 0.2527]], dtype=torch.float64, requires_grad=True)
5 bais: tensor([-0.0502], dtype=torch.float64, requires_grad=True)
6 loss: tensor(0.8124, dtype=torch.float64, grad_fn=<NegBackward0>)
6  weights: tensor([[-0.0263],
        [-0.8521],
        [ 0.5690],
        [ 0.4253],
        [ 0.3618],
        [-1.9217],
        [ 0.3373],
        [-1.0075],
        [-1.3408],
        [ 0.5349],
        [ 0.5439],
        [-1.4102],
        [ 0.5119],
        [ 0.4756],
        [-3.2686],
        [ 0.4980],
        [-1.3561],
        [ 0.3330],
        [-0.6794],
        [-0.0367],
        [ 0.5990],
        [-0.5920],
        [-0.6305],
        [-0.2203],
        [-1.8195],
        [ 0.4653],
        [-0.0757],
        [ 2.2559],
        [ 2.0696],
        [ 0.2528]], dtype=torch.float64, requires_grad=True)
6 bais: tensor([-0.0518], dtype=torch.float64, requires_grad=True)
7 loss: tensor(0.8124, dtype=torch.float64, grad_fn=<NegBackward0>)
7  weights: tensor([[-0.0263],
        [-0.8522],
        [ 0.5690],
        [ 0.4253],
        [ 0.3618],
        [-1.9216],
        [ 0.3373],
        [-1.0075],
        [-1.3407],
        [ 0.5350],
        [ 0.5438],
        [-1.4101],
        [ 0.5118],
        [ 0.4756],
        [-3.2683],
        [ 0.4980],
        [-1.3561],
        [ 0.3330],
        [-0.6793],
        [-0.0365],
        [ 0.5990],
        [-0.5922],
        [-0.6305],
        [-0.2203],
        [-1.8194],
        [ 0.4653],
        [-0.0757],
        [ 2.2560],
        [ 2.0697],
        [ 0.2528]], dtype=torch.float64, requires_grad=True)
7 bais: tensor([-0.0534], dtype=torch.float64, requires_grad=True)
8 loss: tensor(0.8123, dtype=torch.float64, grad_fn=<NegBackward0>)
8  weights: tensor([[-0.0263],
        [-0.8523],
        [ 0.5690],
        [ 0.4254],
        [ 0.3618],
        [-1.9216],
        [ 0.3373],
        [-1.0075],
        [-1.3406],
        [ 0.5351],
        [ 0.5438],
        [-1.4100],
        [ 0.5118],
        [ 0.4756],
        [-3.2680],
        [ 0.4981],
        [-1.3560],
        [ 0.3330],
        [-0.6791],
        [-0.0364],
        [ 0.5990],
        [-0.5923],
        [-0.6305],
        [-0.2202],
        [-1.8193],
        [ 0.4653],
        [-0.0757],
        [ 2.2560],
        [ 2.0698],
        [ 0.2529]], dtype=torch.float64, requires_grad=True)
8 bais: tensor([-0.0551], dtype=torch.float64, requires_grad=True)
9 loss: tensor(0.8123, dtype=torch.float64, grad_fn=<NegBackward0>)
9  weights: tensor([[-0.0263],
        [-0.8524],
        [ 0.5690],
        [ 0.4254],
        [ 0.3619],
        [-1.9215],
        [ 0.3373],
        [-1.0075],
        [-1.3405],
        [ 0.5352],
        [ 0.5438],
        [-1.4099],
        [ 0.5118],
        [ 0.4756],
        [-3.2677],
        [ 0.4982],
        [-1.3560],
        [ 0.3331],
        [-0.6790],
        [-0.0362],
        [ 0.5991],
        [-0.5924],
        [-0.6305],
        [-0.2202],
        [-1.8193],
        [ 0.4653],
        [-0.0757],
        [ 2.2560],
        [ 2.0699],
        [ 0.2529]], dtype=torch.float64, requires_grad=True)
9 bais: tensor([-0.0567], dtype=torch.float64, requires_grad=True)
10 loss: tensor(0.8123, dtype=torch.float64, grad_fn=<NegBackward0>)
10  weights: tensor([[-0.0263],
        [-0.8524],
        [ 0.5690],
        [ 0.4254],
        [ 0.3619],
        [-1.9215],
        [ 0.3373],
        [-1.0075],
        [-1.3405],
        [ 0.5353],
        [ 0.5437],
        [-1.4098],
        [ 0.5117],
        [ 0.4756],
        [-3.2674],
        [ 0.4982],
        [-1.3560],
        [ 0.3331],
        [-0.6789],
        [-0.0360],
        [ 0.5991],
        [-0.5925],
        [-0.6305],
        [-0.2201],
        [-1.8192],
        [ 0.4653],
        [-0.0757],
        [ 2.2560],
        [ 2.0700],
        [ 0.2530]], dtype=torch.float64, requires_grad=True)
10 bais: tensor([-0.0583], dtype=torch.float64, requires_grad=True)
11 loss: tensor(0.8122, dtype=torch.float64, grad_fn=<NegBackward0>)
11  weights: tensor([[-0.0263],
        [-0.8525],
        [ 0.5690],
        [ 0.4255],
        [ 0.3619],
        [-1.9214],
        [ 0.3373],
        [-1.0075],
        [-1.3404],
        [ 0.5354],
        [ 0.5437],
        [-1.4097],
        [ 0.5117],
        [ 0.4756],
        [-3.2671],
        [ 0.4983],
        [-1.3559],
        [ 0.3331],
        [-0.6787],
        [-0.0359],
        [ 0.5991],
        [-0.5926],
        [-0.6305],
        [-0.2201],
        [-1.8191],
        [ 0.4653],
        [-0.0757],
        [ 2.2561],
        [ 2.0701],
        [ 0.2530]], dtype=torch.float64, requires_grad=True)
11 bais: tensor([-0.0599], dtype=torch.float64, requires_grad=True)
12 loss: tensor(0.8122, dtype=torch.float64, grad_fn=<NegBackward0>)
12  weights: tensor([[-0.0263],
        [-0.8526],
        [ 0.5691],
        [ 0.4255],
        [ 0.3619],
        [-1.9214],
        [ 0.3373],
        [-1.0075],
        [-1.3403],
        [ 0.5355],
        [ 0.5437],
        [-1.4096],
        [ 0.5117],
        [ 0.4756],
        [-3.2667],
        [ 0.4984],
        [-1.3559],
        [ 0.3332],
        [-0.6786],
        [-0.0357],
        [ 0.5991],
        [-0.5927],
        [-0.6305],
        [-0.2201],
        [-1.8190],
        [ 0.4653],
        [-0.0757],
        [ 2.2561],
        [ 2.0702],
        [ 0.2531]], dtype=torch.float64, requires_grad=True)
12 bais: tensor([-0.0616], dtype=torch.float64, requires_grad=True)
13 loss: tensor(0.8122, dtype=torch.float64, grad_fn=<NegBackward0>)
13  weights: tensor([[-0.0263],
        [-0.8527],
        [ 0.5691],
        [ 0.4255],
        [ 0.3620],
        [-1.9214],
        [ 0.3373],
        [-1.0074],
        [-1.3402],
        [ 0.5356],
        [ 0.5436],
        [-1.4095],
        [ 0.5116],
        [ 0.4756],
        [-3.2664],
        [ 0.4984],
        [-1.3559],
        [ 0.3332],
        [-0.6785],
        [-0.0355],
        [ 0.5991],
        [-0.5928],
        [-0.6305],
        [-0.2200],
        [-1.8189],
        [ 0.4653],
        [-0.0758],
        [ 2.2561],
        [ 2.0703],
        [ 0.2531]], dtype=torch.float64, requires_grad=True)
13 bais: tensor([-0.0632], dtype=torch.float64, requires_grad=True)
14 loss: tensor(0.8122, dtype=torch.float64, grad_fn=<NegBackward0>)
14  weights: tensor([[-0.0263],
        [-0.8528],
        [ 0.5691],
        [ 0.4256],
        [ 0.3620],
        [-1.9213],
        [ 0.3373],
        [-1.0074],
        [-1.3401],
        [ 0.5357],
        [ 0.5436],
        [-1.4094],
        [ 0.5116],
        [ 0.4756],
        [-3.2661],
        [ 0.4985],
        [-1.3558],
        [ 0.3332],
        [-0.6783],
        [-0.0353],
        [ 0.5991],
        [-0.5929],
        [-0.6305],
        [-0.2200],
        [-1.8189],
        [ 0.4653],
        [-0.0758],
        [ 2.2561],
        [ 2.0704],
        [ 0.2532]], dtype=torch.float64, requires_grad=True)
14 bais: tensor([-0.0648], dtype=torch.float64, requires_grad=True)
15 loss: tensor(0.8121, dtype=torch.float64, grad_fn=<NegBackward0>)
15  weights: tensor([[-0.0263],
        [-0.8528],
        [ 0.5691],
        [ 0.4256],
        [ 0.3620],
        [-1.9213],
        [ 0.3372],
        [-1.0074],
        [-1.3400],
        [ 0.5358],
        [ 0.5435],
        [-1.4093],
        [ 0.5116],
        [ 0.4756],
        [-3.2658],
        [ 0.4986],
        [-1.3558],
        [ 0.3333],
        [-0.6782],
        [-0.0352],
        [ 0.5991],
        [-0.5930],
        [-0.6305],
        [-0.2199],
        [-1.8188],
        [ 0.4652],
        [-0.0758],
        [ 2.2562],
        [ 2.0705],
        [ 0.2532]], dtype=torch.float64, requires_grad=True)
15 bais: tensor([-0.0664], dtype=torch.float64, requires_grad=True)
16 loss: tensor(0.8121, dtype=torch.float64, grad_fn=<NegBackward0>)
16  weights: tensor([[-0.0263],
        [-0.8529],
        [ 0.5691],
        [ 0.4256],
        [ 0.3621],
        [-1.9212],
        [ 0.3372],
        [-1.0074],
        [-1.3400],
        [ 0.5359],
        [ 0.5435],
        [-1.4092],
        [ 0.5116],
        [ 0.4756],
        [-3.2655],
        [ 0.4986],
        [-1.3557],
        [ 0.3333],
        [-0.6780],
        [-0.0350],
        [ 0.5991],
        [-0.5931],
        [-0.6305],
        [-0.2199],
        [-1.8187],
        [ 0.4652],
        [-0.0758],
        [ 2.2562],
        [ 2.0706],
        [ 0.2533]], dtype=torch.float64, requires_grad=True)
16 bais: tensor([-0.0681], dtype=torch.float64, requires_grad=True)
17 loss: tensor(0.8121, dtype=torch.float64, grad_fn=<NegBackward0>)
17  weights: tensor([[-0.0263],
        [-0.8530],
        [ 0.5691],
        [ 0.4256],
        [ 0.3621],
        [-1.9212],
        [ 0.3372],
        [-1.0074],
        [-1.3399],
        [ 0.5360],
        [ 0.5435],
        [-1.4091],
        [ 0.5115],
        [ 0.4756],
        [-3.2652],
        [ 0.4987],
        [-1.3557],
        [ 0.3333],
        [-0.6779],
        [-0.0348],
        [ 0.5991],
        [-0.5933],
        [-0.6304],
        [-0.2199],
        [-1.8186],
        [ 0.4652],
        [-0.0758],
        [ 2.2562],
        [ 2.0707],
        [ 0.2533]], dtype=torch.float64, requires_grad=True)
17 bais: tensor([-0.0697], dtype=torch.float64, requires_grad=True)
18 loss: tensor(0.8120, dtype=torch.float64, grad_fn=<NegBackward0>)
18  weights: tensor([[-0.0263],
        [-0.8531],
        [ 0.5691],
        [ 0.4257],
        [ 0.3621],
        [-1.9212],
        [ 0.3372],
        [-1.0074],
        [-1.3398],
        [ 0.5361],
        [ 0.5434],
        [-1.4090],
        [ 0.5115],
        [ 0.4756],
        [-3.2649],
        [ 0.4988],
        [-1.3557],
        [ 0.3334],
        [-0.6778],
        [-0.0347],
        [ 0.5991],
        [-0.5934],
        [-0.6304],
        [-0.2198],
        [-1.8185],
        [ 0.4652],
        [-0.0758],
        [ 2.2562],
        [ 2.0708],
        [ 0.2534]], dtype=torch.float64, requires_grad=True)
18 bais: tensor([-0.0713], dtype=torch.float64, requires_grad=True)
19 loss: tensor(0.8120, dtype=torch.float64, grad_fn=<NegBackward0>)
19  weights: tensor([[-0.0263],
        [-0.8531],
        [ 0.5691],
        [ 0.4257],
        [ 0.3621],
        [-1.9211],
        [ 0.3372],
        [-1.0074],
        [-1.3397],
        [ 0.5362],
        [ 0.5434],
        [-1.4089],
        [ 0.5115],
        [ 0.4755],
        [-3.2646],
        [ 0.4988],
        [-1.3556],
        [ 0.3334],
        [-0.6776],
        [-0.0345],
        [ 0.5991],
        [-0.5935],
        [-0.6304],
        [-0.2198],
        [-1.8185],
        [ 0.4652],
        [-0.0758],
        [ 2.2562],
        [ 2.0709],
        [ 0.2535]], dtype=torch.float64, requires_grad=True)
19 bais: tensor([-0.0729], dtype=torch.float64, requires_grad=True)
20 loss: tensor(0.8120, dtype=torch.float64, grad_fn=<NegBackward0>)
20  weights: tensor([[-0.0263],
        [-0.8532],
        [ 0.5691],
        [ 0.4257],
        [ 0.3622],
        [-1.9211],
        [ 0.3372],
        [-1.0073],
        [-1.3396],
        [ 0.5363],
        [ 0.5434],
        [-1.4088],
        [ 0.5114],
        [ 0.4755],
        [-3.2643],
        [ 0.4989],
        [-1.3556],
        [ 0.3334],
        [-0.6775],
        [-0.0343],
        [ 0.5992],
        [-0.5936],
        [-0.6304],
        [-0.2198],
        [-1.8184],
        [ 0.4652],
        [-0.0759],
        [ 2.2563],
        [ 2.0710],
        [ 0.2535]], dtype=torch.float64, requires_grad=True)
20 bais: tensor([-0.0746], dtype=torch.float64, requires_grad=True)
21 loss: tensor(0.8120, dtype=torch.float64, grad_fn=<NegBackward0>)
21  weights: tensor([[-0.0263],
        [-0.8533],
        [ 0.5691],
        [ 0.4258],
        [ 0.3622],
        [-1.9210],
        [ 0.3372],
        [-1.0073],
        [-1.3395],
        [ 0.5364],
        [ 0.5433],
        [-1.4087],
        [ 0.5114],
        [ 0.4755],
        [-3.2640],
        [ 0.4990],
        [-1.3556],
        [ 0.3335],
        [-0.6774],
        [-0.0342],
        [ 0.5992],
        [-0.5937],
        [-0.6304],
        [-0.2197],
        [-1.8183],
        [ 0.4652],
        [-0.0759],
        [ 2.2563],
        [ 2.0711],
        [ 0.2536]], dtype=torch.float64, requires_grad=True)
21 bais: tensor([-0.0762], dtype=torch.float64, requires_grad=True)
22 loss: tensor(0.8119, dtype=torch.float64, grad_fn=<NegBackward0>)
22  weights: tensor([[-0.0263],
        [-0.8534],
        [ 0.5691],
        [ 0.4258],
        [ 0.3622],
        [-1.9210],
        [ 0.3372],
        [-1.0073],
        [-1.3395],
        [ 0.5365],
        [ 0.5433],
        [-1.4086],
        [ 0.5114],
        [ 0.4755],
        [-3.2637],
        [ 0.4991],
        [-1.3555],
        [ 0.3335],
        [-0.6772],
        [-0.0340],
        [ 0.5992],
        [-0.5938],
        [-0.6304],
        [-0.2197],
        [-1.8182],
        [ 0.4652],
        [-0.0759],
        [ 2.2563],
        [ 2.0712],
        [ 0.2536]], dtype=torch.float64, requires_grad=True)
22 bais: tensor([-0.0778], dtype=torch.float64, requires_grad=True)
23 loss: tensor(0.8119, dtype=torch.float64, grad_fn=<NegBackward0>)
23  weights: tensor([[-0.0263],
        [-0.8534],
        [ 0.5691],
        [ 0.4258],
        [ 0.3623],
        [-1.9210],
        [ 0.3371],
        [-1.0073],
        [-1.3394],
        [ 0.5366],
        [ 0.5433],
        [-1.4085],
        [ 0.5113],
        [ 0.4755],
        [-3.2634],
        [ 0.4991],
        [-1.3555],
        [ 0.3335],
        [-0.6771],
        [-0.0338],
        [ 0.5992],
        [-0.5939],
        [-0.6304],
        [-0.2196],
        [-1.8181],
        [ 0.4652],
        [-0.0759],
        [ 2.2563],
        [ 2.0713],
        [ 0.2537]], dtype=torch.float64, requires_grad=True)
23 bais: tensor([-0.0795], dtype=torch.float64, requires_grad=True)
24 loss: tensor(0.8119, dtype=torch.float64, grad_fn=<NegBackward0>)
24  weights: tensor([[-0.0263],
        [-0.8535],
        [ 0.5691],
        [ 0.4258],
        [ 0.3623],
        [-1.9209],
        [ 0.3371],
        [-1.0073],
        [-1.3393],
        [ 0.5367],
        [ 0.5432],
        [-1.4084],
        [ 0.5113],
        [ 0.4755],
        [-3.2630],
        [ 0.4992],
        [-1.3554],
        [ 0.3336],
        [-0.6770],
        [-0.0336],
        [ 0.5992],
        [-0.5940],
        [-0.6304],
        [-0.2196],
        [-1.8181],
        [ 0.4652],
        [-0.0759],
        [ 2.2564],
        [ 2.0714],
        [ 0.2537]], dtype=torch.float64, requires_grad=True)
24 bais: tensor([-0.0811], dtype=torch.float64, requires_grad=True)

test

In [62]:
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  loss=model.loss(y_pred,y_test_tensor)
  print("loss:",loss)

loss: tensor(0.8233, dtype=torch.float64)